name: CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch: ~

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.validate.outputs.commit }}

    steps:
    - uses: actions/checkout@v4

    - name: validate
      id: validate
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        python3 ./scripts/validate_commit.py

  tests:
    runs-on: windows-latest
    needs: validate
    steps:
    - uses: actions/checkout@v4
      if: "${{ !startsWith(needs.validate.outputs.commit, 'chore:') }}"

    - name: setup-python
      if: "${{ !startsWith(needs.validate.outputs.commit, 'chore:') }}"
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: install
      if: "${{ !startsWith(needs.validate.outputs.commit, 'chore:') }}"
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: lint
      if: "${{ !startsWith(needs.validate.outputs.commit, 'chore:') }}"
      run: |
        flake8

    - name: test
      if: "${{ !startsWith(needs.validate.outputs.commit, 'chore:') }}"
      env:
        A4KSUBTITLES_SUBDL_APIKEY: ${{ secrets.A4KSUBTITLES_SUBDL_APIKEY }}
      run: |
        coverage run -m pytest -v -s --log-level=DEBUG
