name: Subscene
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cron-tests-subscene.yml'
  schedule:
    - cron:  '0 7 * * *'
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: test
      run: |
        pytest -v -k 'test_subscene' ./tests/test_suite.py
