name: Data Update
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cron-update-data.yml'
  schedule:
    - cron:  '0 7 * * *'
  workflow_dispatch: ~

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ }}

    - name: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: install
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests --user

    - name: update
      run: |
        python3 ./scripts/update_addic7ed.py

    - name: push
      run: |
        git config --global user.email "47229722+newt-sc@users.noreply.github.com"
        git config --global user.name "newt-sc"
        git commit -am "chore: update data" || true
        git push || true
