name: Addic7ed
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cron-tests-addic7ed.yml'
  schedule:
    - cron:  '0 7 * * *'
  workflow_dispatch: ~

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: install
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: test
      run: |
        pytest -v -k 'test_addic7ed' ./tests/test_suite.py
